import type { RoleDef } from '../types/role.js';

export const ALL_ROLES: Record<string, RoleDef> = {
  // ==========================================
  // 1. TIM DESA — INVESTIGATIF
  // ==========================================
  seer: {
    id: 'seer',
    name: 'Seer',
    indonesianName: 'Peramal',
    description: 'Setiap malam dapat menerawang 1 pemain untuk mengetahui apakah dia Werewolf atau bukan.',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 40,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 7,
    balanceCategory: 'investigative',
    minPlayers: 5,
    conflictsWith: [],
    compensationRule: null,
  },
  detective: {
    id: 'detective',
    name: 'Detective',
    indonesianName: 'Detektif / Sheriff',
    description: 'Menyelidiki 1 pemain tiap malam. Mengetahui apakah target mencurigakan (Werewolf atau Neutral Killer).',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 41,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 7,
    balanceCategory: 'investigative',
    minPlayers: 7,
    conflictsWith: ['seer'],
    compensationRule: null,
  },
  aura_seer: {
    id: 'aura_seer',
    name: 'Aura Seer',
    indonesianName: 'Peramal Aura',
    description: 'Menerawang aura pemain untuk mengetahui tim asalnya (Desa, Serigala, atau Netral) tanpa tahu peran persisnya.',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 42,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 6,
    balanceCategory: 'investigative',
    minPlayers: 8,
    conflictsWith: [],
    compensationRule: null,
  },
  apprentice_seer: {
    id: 'apprentice_seer',
    name: 'Apprentice Seer',
    indonesianName: 'Murid Peramal',
    description: 'Warga biasa selama Peramal masih hidup. Begitu Peramal gugur, Anda otomatis mewarisi kekuatan menerawang.',
    team: 'village',
    actionType: 'none',
    targetType: 'none',
    resolutionPriority: 999,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 4,
    balanceCategory: 'investigative',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  psychic: {
    id: 'psychic',
    name: 'Psychic',
    indonesianName: 'Penyihir / Cenayang',
    description: 'Kekuatan tinggi: Menerawang 1 pemain dan langsung mengetahui identitas peran persisnya.',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 43,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 9,
    balanceCategory: 'investigative',
    minPlayers: 12,
    conflictsWith: ['seer'],
    compensationRule: null,
  },
  tracker: {
    id: 'tracker',
    name: 'Tracker',
    indonesianName: 'Pelacak',
    description: 'Membuntuti 1 pemain tiap malam dan mengetahui siapa saja yang dikunjungi oleh pemain tersebut.',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 44,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 5,
    balanceCategory: 'investigative',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  lookout: {
    id: 'lookout',
    name: 'Lookout',
    indonesianName: 'Pengintai',
    description: 'Mengawasi rumah 1 pemain tiap malam dan melihat siapa saja yang datang mengunjungi pemain itu.',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 45,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 5,
    balanceCategory: 'investigative',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  fox: {
    id: 'fox',
    name: 'Fox',
    indonesianName: 'Rubah',
    description: 'Menunjuk 3 pemain sekaligus. Jika ada minimal 1 serigala, Anda tetap punya kekuatan; jika nihil, kekuatan hilang.',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 46,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 6,
    balanceCategory: 'investigative',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  beholder: {
    id: 'beholder',
    name: 'Beholder',
    indonesianName: 'Beholder',
    description: 'Pada malam pertama, Anda langsung diberitahu siapa yang menjadi Peramal sejati di desa.',
    team: 'village',
    actionType: 'none',
    targetType: 'none',
    resolutionPriority: 999,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 3,
    balanceCategory: 'investigative',
    minPlayers: 8,
    conflictsWith: [],
    compensationRule: null,
  },
  bear_tamer: {
    id: 'bear_tamer',
    name: 'Bear Tamer',
    indonesianName: 'Penjinak Beruang',
    description: 'Setiap pagi fajar menyingsing, beruang peliharaannya akan menggeram buas jika salah satu tetangga duduknya (kiri atau kanan) adalah serigala!',
    team: 'village',
    actionType: 'none',
    targetType: 'none',
    resolutionPriority: 999,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 7,
    balanceCategory: 'investigative',
    minPlayers: 8,
    conflictsWith: [],
    compensationRule: null,
  },
  paranormal_investigator: {
    id: 'paranormal_investigator',
    name: 'Paranormal Investigator',
    indonesianName: 'Penyelidik Paranormal',
    description: 'Memeriksa 1 pemain tiap malam. Jika target adalah Warga Desa biasa (Villager), kekuatan Anda langsung padam selamanya!',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 47,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 6,
    balanceCategory: 'investigative',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  little_girl: {
    id: 'little_girl',
    name: 'Little Girl',
    indonesianName: 'Gadis Kecil',
    description: 'Setiap malam dapat mengintip bayangan kawanan serigala dan menerima petunjuk siapa salah satu serigala di desa.',
    team: 'village',
    actionType: 'none',
    targetType: 'none',
    resolutionPriority: 999,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 7,
    balanceCategory: 'investigative',
    minPlayers: 8,
    conflictsWith: [],
    compensationRule: null,
  },

  // ==========================================
  // 2. TIM DESA — PROTEKTIF
  // ==========================================
  guardian: {
    id: 'guardian',
    name: 'Guardian',
    indonesianName: 'Dokter / Pelindung',
    description: 'Setiap malam dapat melindungi 1 pemain dari serangan Werewolf. Tidak boleh melindungi target yang sama dua malam berturut-turut.',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 20,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 6,
    balanceCategory: 'protective',
    minPlayers: 7,
    conflictsWith: [],
    compensationRule: null,
  },
  bodyguard: {
    id: 'bodyguard',
    name: 'Bodyguard',
    indonesianName: 'Pengawal',
    description: 'Melindungi 1 pemain tiap malam (tidak boleh target yang sama berturut-turut). Jika target diserang, penyerang dan Bodyguard sama-sama tewas.',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 21,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 6,
    balanceCategory: 'protective',
    minPlayers: 10,
    conflictsWith: ['guardian'],
    compensationRule: null,
  },
  defender: {
    id: 'defender',
    name: 'Defender',
    indonesianName: 'Penjaga Benteng',
    description: 'Melindungi 1 pemain dari serangan. Tidak boleh memilih target yang sama dua malam berturut-turut.',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 22,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 5,
    balanceCategory: 'protective',
    minPlayers: 8,
    conflictsWith: [],
    compensationRule: null,
  },
  jailer: {
    id: 'jailer',
    name: 'Jailer',
    indonesianName: 'Sipir Penjara',
    description: 'Mengurung 1 pemain tiap malam (tidak boleh pemain yang sama berturut-turut). Tahanan kebal dari serangan malam, namun aksinya juga diblokir.',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 15,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 8,
    balanceCategory: 'protective',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  crusader: {
    id: 'crusader',
    name: 'Crusader',
    indonesianName: 'Ksatria Salib',
    description: 'Melindungi 1 pemain (tidak boleh target yang sama berturut-turut). Jika ada pengunjung yang datang ke target tersebut, Crusader akan menyerangnya.',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 23,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 6,
    balanceCategory: 'protective',
    minPlayers: 12,
    conflictsWith: [],
    compensationRule: null,
  },
  elder: {
    id: 'elder',
    name: 'Elder',
    indonesianName: 'Tetua Desa',
    description: 'Otomatis selamat dari serangan serigala pertama. Jika dieksekusi voting, seluruh peran spesial desa kehilangan kekuatan.',
    team: 'village',
    actionType: 'none',
    targetType: 'none',
    resolutionPriority: 999,
    reactiveTrigger: 'onDeath',
    visibility: { seeTeammates: false },
    balanceWeight: 5,
    balanceCategory: 'protective',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  firefighter: {
    id: 'firefighter',
    name: 'Firefighter',
    indonesianName: 'Pemadam Kebakaran',
    description: 'Tiap malam dapat membasuh 1 rumah pemain dari siraman bensin Pembakar (Arsonist) atau melindunginya dari kobaran api.',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 24,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 5,
    balanceCategory: 'protective',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },

  // ==========================================
  // 3. TIM DESA — KILLER DESA
  // ==========================================
  vigilante: {
    id: 'vigilante',
    name: 'Vigilante',
    indonesianName: 'Main Hakim Sendiri',
    description: 'Dapat menembak 1 pemain mulai Malam 2. Jika salah menembak sesama warga desa, rasa bersalah akan merenggut nyawa sang Vigilante malam berikutnya!',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 32,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 6,
    balanceCategory: 'village_killer',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  hunter: {
    id: 'hunter',
    name: 'Hunter',
    indonesianName: 'Pemburu',
    description: 'Jika mati karena serangan malam atau dieksekusi voting, menyeret 1 pemain lain untuk ikut mati.',
    team: 'village',
    actionType: 'reactive',
    targetType: 'single_player',
    resolutionPriority: 50,
    reactiveTrigger: 'onDeath',
    visibility: { seeTeammates: false },
    balanceWeight: 5,
    balanceCategory: 'reactive',
    minPlayers: 10,
    conflictsWith: ['cupid'],
    compensationRule: null,
  },
  veteran: {
    id: 'veteran',
    name: 'Veteran',
    indonesianName: 'Veteran Perang',
    description: 'Dapat bersiaga (alert) di malam hari. Siapa pun yang mengunjunginya malam itu akan langsung ditembak mati.',
    team: 'village',
    actionType: 'independent',
    targetType: 'none',
    resolutionPriority: 18,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 7,
    balanceCategory: 'village_killer',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  slayer: {
    id: 'slayer',
    name: 'Slayer',
    indonesianName: 'Pembantai Iblis (Slayer)',
    description: 'Sekali seumur game, dapat menebak dan menembak 1 pemain di malam hari. Jika target adalah Serigala, target mati seketika!',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 33,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 7,
    balanceCategory: 'village_killer',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },

  // ==========================================
  // 4. TIM DESA — ASOSIASI
  // ==========================================
  mason: {
    id: 'mason',
    name: 'Mason',
    indonesianName: 'Mason',
    description: 'Saling mengenal identitas sesama Mason sejak awal malam untuk membangun persekutuan kepercayaan.',
    team: 'village',
    actionType: 'none',
    targetType: 'none',
    resolutionPriority: 999,
    reactiveTrigger: null,
    visibility: { seeTeammates: true },
    balanceWeight: 3,
    balanceCategory: 'association',
    minPlayers: 7,
    conflictsWith: [],
    compensationRule: {
      addRoleId: 'werewolf',
      condition: 'belowPlayerCount',
      threshold: 10,
    },
  },
  two_sisters: {
    id: 'two_sisters',
    name: 'Two Sisters',
    indonesianName: 'Dua Saudari',
    description: 'Dua bersaudari yang saling mengetahui identitas asli sejak malam pertama.',
    team: 'village',
    actionType: 'none',
    targetType: 'none',
    resolutionPriority: 999,
    reactiveTrigger: null,
    visibility: { seeTeammates: true },
    balanceWeight: 3,
    balanceCategory: 'association',
    minPlayers: 9,
    conflictsWith: ['mason'],
    compensationRule: null,
  },
  cupid: {
    id: 'cupid',
    name: 'Cupid',
    indonesianName: 'Kupido',
    description: 'Pada malam pertama memilih 2 orang menjadi pasangan Lovers. Jika satu mati, pasangannya ikut mati.',
    team: 'village',
    actionType: 'independent',
    targetType: 'two_players',
    resolutionPriority: 10,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 4,
    balanceCategory: 'association',
    minPlayers: 10,
    conflictsWith: ['hunter'],
    compensationRule: null,
  },

  // ==========================================
  // 5. TIM DESA — UTILITY & DISRUPTIVE
  // ==========================================
  witch: {
    id: 'witch',
    name: 'Witch',
    indonesianName: 'Penyihir Desa',
    description: 'Memiliki 1 ramuan penyembuh (menyelamatkan korban) dan 1 ramuan racun (membunuh 1 orang), masing-masing sekali pakai.',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 33,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 7,
    balanceCategory: 'disruptive',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  transporter: {
    id: 'transporter',
    name: 'Transporter',
    indonesianName: 'Transporter',
    description: 'Menukar target dari 2 pemain di malam hari. Semua aksi ke pemain A akan dialihkan ke B dan sebaliknya.',
    team: 'village',
    actionType: 'independent',
    targetType: 'two_players',
    resolutionPriority: 5, // Processed before all actions
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 8,
    balanceCategory: 'disruptive',
    minPlayers: 12,
    conflictsWith: [],
    compensationRule: null,
  },
  escort: {
    id: 'escort',
    name: 'Escort',
    indonesianName: 'Pengawal Pengalih / Escort',
    description: 'Mengunjungi 1 pemain tiap malam dan memblokir aksi malamnya (tidak boleh target yang sama dua malam berturut-turut).',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 8, // Processed very early
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 6,
    balanceCategory: 'disruptive',
    minPlayers: 8,
    conflictsWith: [],
    compensationRule: null,
  },
  thief: {
    id: 'thief',
    name: 'Thief',
    indonesianName: 'Pencuri',
    description: 'Pada malam pertama, dapat mencuri dan menukar perannya dengan salah satu pemain lain secara rahasia.',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 4,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 5,
    balanceCategory: 'disruptive',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  gypsy: {
    id: 'gypsy',
    name: 'Gypsy',
    indonesianName: 'Gipsi (Gypsy)',
    description: 'Dapat memanggil arwah atau peran tertentu di malam hari untuk membuka kontak batin rahasia.',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 9,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 5,
    balanceCategory: 'disruptive',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },

  // ==========================================
  // 6. TIM DESA — PEMBERDAYAAN & VOTING
  // ==========================================
  mayor: {
    id: 'mayor',
    name: 'Mayor',
    indonesianName: 'Walikota',
    description: 'Suara voting eksekusi Anda dihitung bernilai 2 suara secara publik.',
    team: 'village',
    actionType: 'none',
    targetType: 'none',
    resolutionPriority: 999,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 4,
    balanceCategory: 'vote_empowerment',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  scapegoat: {
    id: 'scapegoat',
    name: 'Scapegoat',
    indonesianName: 'Kambing Hitam',
    description: 'Jika hasil pemungutan suara desa berakhir seri (tie), dialah yang dieksekusi sebagai pengganti.',
    team: 'village',
    actionType: 'none',
    targetType: 'none',
    resolutionPriority: 999,
    reactiveTrigger: 'onVoteTie',
    visibility: { seeTeammates: false },
    balanceWeight: 2,
    balanceCategory: 'vote_empowerment',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  stuttering_judge: {
    id: 'stuttering_judge',
    name: 'Stuttering Judge',
    indonesianName: 'Hakim Gagap',
    description: 'Sekali seumur game, dapat memicu ronde voting eksekusi kedua pada hari yang sama.',
    team: 'village',
    actionType: 'independent',
    targetType: 'none',
    resolutionPriority: 999,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 3,
    balanceCategory: 'vote_empowerment',
    minPlayers: 12,
    conflictsWith: [],
    compensationRule: null,
  },
  priest: {
    id: 'priest',
    name: 'Priest',
    indonesianName: 'Pendeta Desa',
    description: 'Dapat melempar air suci ke 1 pemain di malam hari. Jika target adalah Serigala, ia mati; jika orang baik, Pendeta yang gugur!',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 34,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 5,
    balanceCategory: 'vote_empowerment',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },

  // ==========================================
  // 7. TIM DESA — OUTSIDER / HANDICAP & UNIQUE
  // ==========================================
  villager: {
    id: 'villager',
    name: 'Villager',
    indonesianName: 'Warga Desa',
    description: 'Warga biasa tanpa kemampuan malam khusus. Andalkan logika deduksi, argumen, dan suara voting Anda.',
    team: 'village',
    actionType: 'none',
    targetType: 'none',
    resolutionPriority: 999,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 0,
    balanceCategory: 'outsider',
    minPlayers: 5,
    conflictsWith: [],
    compensationRule: null,
  },
  drunk: {
    id: 'drunk',
    name: 'Drunk',
    indonesianName: 'Orang Mabuk',
    description: 'Mengira memiliki peran tertentu, padahal sebenarnya hanya warga desa biasa yang tidak berdaya.',
    team: 'village',
    actionType: 'none',
    targetType: 'none',
    resolutionPriority: 999,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: -1,
    balanceCategory: 'outsider',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  lycan: {
    id: 'lycan',
    name: 'Lycan',
    indonesianName: 'Lycan',
    description: 'Warga desa setia namun darahnya terkutuk sehingga selalu terdeteksi sebagai Serigala oleh Peramal.',
    team: 'village',
    actionType: 'none',
    targetType: 'none',
    resolutionPriority: 999,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: -2,
    balanceCategory: 'outsider',
    minPlayers: 10,
    conflictsWith: ['alpha_wolf'],
    compensationRule: null,
  },
  recluse: {
    id: 'recluse',
    name: 'Recluse',
    indonesianName: 'Pertapa / Recluse',
    description: 'Warga desa yang hidup menyendiri. Sering kali terdeteksi sebagai aura jahat oleh peran investigatif.',
    team: 'village',
    actionType: 'none',
    targetType: 'none',
    resolutionPriority: 999,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: -1,
    balanceCategory: 'outsider',
    minPlayers: 12,
    conflictsWith: [],
    compensationRule: null,
  },
  village_idiot: {
    id: 'village_idiot',
    name: 'Village Idiot',
    indonesianName: 'Orang Bodoh Desa',
    description: 'Jika divote mati oleh desa, ia selamat dari tiang gantungan tetapi kehilangan hak bicara dan hak voting.',
    team: 'village',
    actionType: 'none',
    targetType: 'none',
    resolutionPriority: 999,
    reactiveTrigger: 'onDeath',
    visibility: { seeTeammates: false },
    balanceWeight: 1,
    balanceCategory: 'outsider',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  wild_child: {
    id: 'wild_child',
    name: 'Wild Child',
    indonesianName: 'Anak Liar',
    description: 'Memilih 1 panutan malam pertama. Jika panutannya gugur, ia mengamuk dan berubah menjadi Serigala.',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 12,
    reactiveTrigger: 'onDeath',
    visibility: { seeTeammates: false },
    balanceWeight: 3,
    balanceCategory: 'outsider',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  angel: {
    id: 'angel',
    name: 'Angel',
    indonesianName: 'Malaikat',
    description: 'Menang seketika seorang diri jika ia mati pada malam pertama atau dieksekusi pada hari pertama!',
    team: 'village',
    actionType: 'none',
    targetType: 'none',
    resolutionPriority: 999,
    reactiveTrigger: 'onDeath',
    visibility: { seeTeammates: false },
    balanceWeight: 4,
    balanceCategory: 'reactive',
    minPlayers: 8,
    conflictsWith: ['tanner', 'jester'],
    compensationRule: null,
  },
  knight_rusty_sword: {
    id: 'knight_rusty_sword',
    name: 'Knight with Rusty Sword',
    indonesianName: 'Ksatria Pedang Karat',
    description: 'Jika dibunuh oleh serigala pada malam hari, serigala di sebelah kirinya akan ikut tewas karena racun karat keesokan paginya.',
    team: 'village',
    actionType: 'none',
    targetType: 'none',
    resolutionPriority: 999,
    reactiveTrigger: 'onKilled',
    visibility: { seeTeammates: false },
    balanceWeight: 4,
    balanceCategory: 'reactive',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  actor: {
    id: 'actor',
    name: 'Actor',
    indonesianName: 'Aktor (Actor)',
    description: 'Setiap ronde malam dapat meminjam dan meniru kemampuan peran yang tidak aktif dalam permainan.',
    team: 'village',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 10,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 6,
    balanceCategory: 'disruptive',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },

  // ==========================================
  // 8. TIM WEREWOLF
  // ==========================================
  werewolf: {
    id: 'werewolf',
    name: 'Werewolf',
    indonesianName: 'Serigala',
    description: 'Bangun setiap malam bersama kawanan serigala untuk memilih 1 korban warga desa.',
    team: 'werewolf',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 30,
    reactiveTrigger: null,
    visibility: { seeTeammates: true },
    balanceWeight: 10,
    balanceCategory: 'werewolf_core',
    minPlayers: 5,
    conflictsWith: [],
    compensationRule: null,
  },
  alpha_wolf: {
    id: 'alpha_wolf',
    name: 'Alpha Wolf',
    indonesianName: 'Serigala Alfa',
    description: 'Pemimpin kawanan. Kebal deteksi: jika diterawang oleh Peramal, terdeteksi sebagai Orang Baik (Innocent).',
    team: 'werewolf',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 30,
    reactiveTrigger: null,
    visibility: { seeTeammates: true },
    balanceWeight: 12,
    balanceCategory: 'werewolf_deceptive',
    minPlayers: 10,
    conflictsWith: ['lycan'],
    compensationRule: null,
  },
  mystic_wolf: {
    id: 'mystic_wolf',
    name: 'Mystic Wolf',
    indonesianName: 'Serigala Mistis',
    description: 'Selain ikut memilih mangsa bersama kawanan, dapat menerawang peran 1 pemain setiap malam.',
    team: 'werewolf',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 41,
    reactiveTrigger: null,
    visibility: { seeTeammates: true },
    balanceWeight: 13,
    balanceCategory: 'werewolf_core',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  wolf_cub: {
    id: 'wolf_cub',
    name: 'Wolf Cub',
    indonesianName: 'Anak Serigala',
    description: 'Jika mati, sisa kawanan serigala akan memangsa 2 orang sekaligus pada malam berikutnya.',
    team: 'werewolf',
    actionType: 'reactive',
    targetType: 'none',
    resolutionPriority: 50,
    reactiveTrigger: 'onDeath',
    visibility: { seeTeammates: true },
    balanceWeight: 11,
    balanceCategory: 'werewolf_deceptive',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  big_bad_wolf: {
    id: 'big_bad_wolf',
    name: 'Big Bad Wolf',
    indonesianName: 'Serigala Buas',
    description: 'Jika korban pilihan kawanan duduk bersebelahan dengannya, ia boleh sekalian memangsa 1 tetangga lainnya.',
    team: 'werewolf',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 31,
    reactiveTrigger: null,
    visibility: { seeTeammates: true },
    balanceWeight: 12,
    balanceCategory: 'werewolf_core',
    minPlayers: 12,
    conflictsWith: [],
    compensationRule: null,
  },
  white_werewolf: {
    id: 'white_werewolf',
    name: 'White Werewolf',
    indonesianName: 'Serigala Putih',
    description: 'Membunuh bersama kawanan, tetapi setiap 2 malam dapat membunuh 1 sesama serigala. Menang sendiri jika jadi satu-satunya penyintas.',
    team: 'werewolf',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 28,
    reactiveTrigger: null,
    visibility: { seeTeammates: true },
    balanceWeight: 14,
    balanceCategory: 'werewolf_core',
    minPlayers: 14,
    conflictsWith: [],
    compensationRule: null,
  },
  cursed_wolf_father: {
    id: 'cursed_wolf_father',
    name: 'Cursed Wolf-Father',
    indonesianName: 'Bapa Serigala Terkutuk',
    description: 'Sekali seumur game, alih-alih membunuh mangsa, ia dapat menginfeksi korban menjadi Serigala baru!',
    team: 'werewolf',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 29,
    reactiveTrigger: null,
    visibility: { seeTeammates: true },
    balanceWeight: 14,
    balanceCategory: 'werewolf_deceptive',
    minPlayers: 12,
    conflictsWith: ['wolf_cub'],
    compensationRule: null,
  },
  minion: {
    id: 'minion',
    name: 'Minion',
    indonesianName: 'Kaki Tangan / Minion',
    description: 'Mengetahui siapa saja kawanan serigala dan menang bersama mereka, namun serigala tidak tahu siapa dia.',
    team: 'werewolf',
    actionType: 'none',
    targetType: 'none',
    resolutionPriority: 999,
    reactiveTrigger: null,
    visibility: { seeTeammates: true },
    balanceWeight: 6,
    balanceCategory: 'werewolf_deceptive',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  wolf_hound: {
    id: 'wolf_hound',
    name: 'Wolf Hound',
    indonesianName: 'Anjing Serigala',
    description: 'Pada malam pertama, Anda memilih sendiri secara bebas apakah ingin berpihak ke Desa atau Serigala.',
    team: 'werewolf',
    actionType: 'independent',
    targetType: 'none',
    resolutionPriority: 11,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 8,
    balanceCategory: 'werewolf_core',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  hoodlum: {
    id: 'hoodlum',
    name: 'Hoodlum',
    indonesianName: 'Pengkhianat (Traitor / Hoodlum)',
    description: 'Warga desa yang diam-diam berpihak pada kawanan serigala dan menang bersama mereka, namun terdeteksi innocent oleh Seer.',
    team: 'werewolf',
    actionType: 'none',
    targetType: 'none',
    resolutionPriority: 999,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 7,
    balanceCategory: 'werewolf_deceptive',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  bogeyman: {
    id: 'bogeyman',
    name: 'Bogeyman',
    indonesianName: 'Bogeyman',
    description: 'Serigala kegelapan yang buas. Jika kawanan serigala gagal menyepakati mangsa (seri/abstain), Bogeyman yang membunuh korbannya sendiri!',
    team: 'werewolf',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 31,
    reactiveTrigger: null,
    visibility: { seeTeammates: true },
    balanceWeight: 11,
    balanceCategory: 'werewolf_core',
    minPlayers: 12,
    conflictsWith: [],
    compensationRule: null,
  },

  // ==========================================
  // 9. TIM NETRAL / INDEPENDEN
  // ==========================================
  lone_wolf: {
    id: 'lone_wolf',
    name: 'Lone Wolf',
    indonesianName: 'Serigala Penyendiri (Lone Wolf)',
    description: 'Bangun bersama kawanan serigala, namun memiliki agenda rahasia sendiri. Menang HANYA jika ia menjadi satu-satunya yang bertahan hidup!',
    team: 'neutral',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 30,
    reactiveTrigger: null,
    visibility: { seeTeammates: true },
    balanceWeight: 9,
    balanceCategory: 'neutral_independent',
    minPlayers: 12,
    conflictsWith: ['white_werewolf'],
    compensationRule: null,
  },
  tanner: {
    id: 'tanner',
    name: 'Tanner',
    indonesianName: 'Penyamak Kulit / Tanner',
    description: 'Menang sendiri seketika jika berhasil membuat warga desa mengeksekusi dirinya di tiang gantungan.',
    team: 'neutral',
    actionType: 'none',
    targetType: 'none',
    resolutionPriority: 999,
    reactiveTrigger: 'onDeath',
    visibility: { seeTeammates: false },
    balanceWeight: 2,
    balanceCategory: 'neutral_independent',
    minPlayers: 8,
    conflictsWith: ['jester'],
    compensationRule: null,
  },
  jester: {
    id: 'jester',
    name: 'Jester',
    indonesianName: 'Badut / Jester',
    description: 'Menang jika dieksekusi voting siang. Sebelum mati, dapat mengutuk 1 orang pemilihnya untuk ikut mati.',
    team: 'neutral',
    actionType: 'reactive',
    targetType: 'single_player',
    resolutionPriority: 50,
    reactiveTrigger: 'onDeath',
    visibility: { seeTeammates: false },
    balanceWeight: 3,
    balanceCategory: 'neutral_independent',
    minPlayers: 10,
    conflictsWith: ['tanner'],
    compensationRule: null,
  },
  serial_killer: {
    id: 'serial_killer',
    name: 'Serial Killer',
    indonesianName: 'Pembunuh Berantai',
    description: 'Membunuh 1 orang setiap malam secara mandiri. Kebal serangan malam biasa. Menang jika jadi yang terakhir hidup.',
    team: 'neutral',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 25,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 8,
    balanceCategory: 'neutral_independent',
    minPlayers: 12,
    conflictsWith: [],
    compensationRule: null,
  },
  arsonist: {
    id: 'arsonist',
    name: 'Arsonist',
    indonesianName: 'Pembakar / Arsonist',
    description: 'Menyiram bensin ke rumah warga tiap malam, lalu pada malam pilihan membakar seluruh target douse sekaligus!',
    team: 'neutral',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 20,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 9,
    balanceCategory: 'neutral_independent',
    minPlayers: 12,
    conflictsWith: [],
    compensationRule: null,
  },
  cult_leader: {
    id: 'cult_leader',
    name: 'Cult Leader',
    indonesianName: 'Pemimpin Kultus',
    description: 'Merekrut 1 pemain tiap malam masuk ke dalam sekte. Menang jika seluruh penyintas telah menjadi pengikut kultus.',
    team: 'neutral',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 36,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 8,
    balanceCategory: 'neutral_independent',
    minPlayers: 12,
    conflictsWith: ['piper', 'vampire'],
    compensationRule: null,
  },
  piper: {
    id: 'piper',
    name: 'Piper',
    indonesianName: 'Peniup Seruling / Piper',
    description: 'Mempesona 2 pemain tiap malam dengan tiupan serulingnya. Menang jika semua warga hidup telah terpesona.',
    team: 'neutral',
    actionType: 'independent',
    targetType: 'two_players',
    resolutionPriority: 37,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 8,
    balanceCategory: 'neutral_independent',
    minPlayers: 12,
    conflictsWith: ['cult_leader'],
    compensationRule: null,
  },
  vampire: {
    id: 'vampire',
    name: 'Vampire',
    indonesianName: 'Vampir',
    description: 'Menggigit target untuk mengubahnya menjadi sesama Vampir. Menang jika bangsa Vampir menjadi mayoritas desa.',
    team: 'neutral',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 38,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 9,
    balanceCategory: 'neutral_independent',
    minPlayers: 12,
    conflictsWith: ['cult_leader'],
    compensationRule: null,
  },
  survivor: {
    id: 'survivor',
    name: 'Survivor',
    indonesianName: 'Penyintas / Survivor',
    description: 'Hanya memiliki 3 rompi antipeluru. Bebas dipakai berturut-turut atau disimpan untuk malam berikutnya. Bertahan hidup sampai akhir game untuk menang.',
    team: 'neutral',
    actionType: 'independent',
    targetType: 'none',
    resolutionPriority: 19,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 4,
    balanceCategory: 'neutral_independent',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  executioner: {
    id: 'executioner',
    name: 'Executioner',
    indonesianName: 'Algojo / Executioner',
    description: 'Diberikan 1 target warga desa secara rahasia. Menang jika target tersebut berhasil digantung lewat voting siang!',
    team: 'neutral',
    actionType: 'none',
    targetType: 'none',
    resolutionPriority: 999,
    reactiveTrigger: 'onDeath',
    visibility: { seeTeammates: false },
    balanceWeight: 5,
    balanceCategory: 'neutral_independent',
    minPlayers: 10,
    conflictsWith: ['tanner', 'jester'],
    compensationRule: null,
  },
  amnesiac: {
    id: 'amnesiac',
    name: 'Amnesiac',
    indonesianName: 'Hilang Ingatan / Amnesiac',
    description: 'Dapat memilih 1 pemain yang sudah mati untuk mengingat dan mengambil alih peran serta kubu pemain tersebut.',
    team: 'neutral',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 49,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 6,
    balanceCategory: 'neutral_independent',
    minPlayers: 12,
    conflictsWith: [],
    compensationRule: null,
  },
  doppelganger: {
    id: 'doppelganger',
    name: 'Doppelganger',
    indonesianName: 'Doppelganger',
    description: 'Pada malam pertama, meniru identitas pemain lain dan mewarisi peran orang tersebut jika orang itu gugur.',
    team: 'neutral',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 10,
    reactiveTrigger: 'onDeath',
    visibility: { seeTeammates: false },
    balanceWeight: 7,
    balanceCategory: 'neutral_independent',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
  ghost: {
    id: 'ghost',
    name: 'Ghost',
    indonesianName: 'Hantu (Ghost)',
    description: 'Gugur secara misterius pada malam pertama, lalu setiap siang hari boleh memberikan petunjuk 1 huruf kepada seluruh warga.',
    team: 'neutral',
    actionType: 'none',
    targetType: 'none',
    resolutionPriority: 999,
    reactiveTrigger: 'onDeath',
    visibility: { seeTeammates: false },
    balanceWeight: 2,
    balanceCategory: 'neutral_independent',
    minPlayers: 8,
    conflictsWith: [],
    compensationRule: null,
  },
  sorcerer: {
    id: 'sorcerer',
    name: 'Sorcerer',
    indonesianName: 'Penyihir Kegelapan / Sorcerer',
    description: 'Penyihir netral yang setiap malam dapat memilih 1 pemain dan menebak perannya. Jika tebakannya tepat, target akan langsung mati tersambar petir!',
    team: 'neutral',
    actionType: 'independent',
    targetType: 'single_player',
    resolutionPriority: 22,
    reactiveTrigger: null,
    visibility: { seeTeammates: false },
    balanceWeight: 8,
    balanceCategory: 'neutral_independent',
    minPlayers: 10,
    conflictsWith: [],
    compensationRule: null,
  },
};
